theme: jekyll-theme-minimal
title: Rafael Souza de Almeida Saraiva
languages: ["en", "de"]
logo: /assets/jumpingdino2.jpeg
#description: 
# github:
#   is_project_page: false

header_page_refs: ['home', 'contato', 'projetos']
